language: python
os: linux
dist: xenial
python:
 - '3.6'
 - '3.7'
install: "make"
script:
 - make test
jobs:
  include:
    - stage: test
      python: '3.6'
    - stage: test
      python: '3.7'
    - stage: test
      python: 'pypy3'
      dist: xenial
