language: python
os: linux
dist: xenial
python:
 - '3.6'
 - '3.7'
install: "make"
script:
 - make test-readme
 - make ci
 cache: pip
jobs:
  include:
    - stage: test
      python: '3.5'
    - stage: test
      python: '3.6'
    - stage: test
      python: '3.7'
    - stage: test
      python: 'pypy3'
      dist: xenial
    - stage: test
      python: '3.8'
deploy:
  provider: pypi
  username: parody_bit
  password:
    secure: Ljd6cCXZzLNkbdBylVesPuKxWp9G4imraFIxe7i3OeO/SeCIg9c7OonOyQl4fUn84lqrUgakgyLAE6oqivKgXSp1IO/Faw+xfgfD1t3rgCReqEpVlV3LNboaa8ZBibcEPlcSOZeGUu5rRmfuBOK6LHR+fVBauV9+QHCOlBKOYVYsPEG81sAdKPsf2TBlAEcgqSB8ECmaV6lorVV86h8gn02uRvdXEWYOj2vIgakpb+A2vmrhq/+Zkt6+ALKlLIEitCYHJlTE0DOfWWyeBCIfPrWZpmYt04Y6L4gX63CtNK9g67t4VEhqpWskC0EnQi7JIlm54+N0k5OJczmk+ZzDM+Ja+DM6JPBSlapjK8EzW27UJfXeBUiNFs4gqNsIloZn3kE2mt4rc8D1xpiSgP4F5+yfAsZezfMmhvtDmIHQx62P+0hCEbvWHob1odwWHLMGD+eoog6RSwdLXTjX54MDR/zb+sRqTLNn49wtzQhI1mdNqfC/ZYrHQnWeUFN5pGpW5tTw9+X9Hp+MsPKuFHlGU+iuaXxqM15z3UJKCDUVVR/zJODyphvsgeqcwTicVALeH/kw9L0cQTnpDmbGdSWOGOxjqxq5W8lX30OBLbRJNXsQpnpmR9sqv8GNeeRZv8VI8djoUVcdJ08dEJ7/cujEDuQJz2hAJaphJTCGYl5dUy8=
  on:
    branch: master